### ISSUE TITLE
Release v0.3 Checklist

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/PyElastica#176]
# Release Checklist

- [x] Final check `README` and `CONTRIBUTING`.
- [x] Bump LICENSE year
- [x] Bump version  (`pyproject.toml`) followed by `poetry lock`
- [x] ~~Dependency version (`poetry update`)~~
  - ~~Might break some dependency chain.
- [x] Check if all `remove in v0.3.0` or `change to XXX in v0.3.0` are resolved.

### Test
- [x] Run the tests
- [x] Run the formatting
- [x] CI Check
```
make test
```
### Build / Installation

- [x] Check if local installation can be done.
```bash
conda create --name temp
conda activate temp
conda install python==<version>
which pip
make poetry-download
make install
```

### Documentation and Website
- [x] Check all documentations are updated
- [x] Update version label on documentation
  - [x] docs/conf.py
  - [x] Python version
- [x] Update version label on website
  - [x] Python version

```diff
- BEYOND THIS, EACH STEP SHOULD BE DONE IN SERIAL (STEP_BY_STEPS). -
```

### Last Edit
- [x] ~~Rebase the commit history (should be done by only one person) right before the PR.~~

### Update
1. [ ] Merge the branch to `master`
2. [ ] Release on github. It should automatically upload pypi

# Post-release Checklist

- [ ] Update RELEASE.md - It should be in based on milestone description.
- [ ] Commit the changes: 
```bash
git add RELEASE.md
git commit -m "Changelog for upcoming release <version>"
```

### Final Check
- [ ] Test that it pip installs
- [ ] Check the PyPI listing page to make sure that the README, release notes, and roadmap display properly.
- [ ] Edit the release-page on GitHub. Paste the release notes with a title for the release.
- [ ] Check Codcov ID and make sure they are running.
- [x] ~~Make mirror branch in private repo.~~

**Comment by armantekinalp** [comment]
I think all codes for this update merged. So I will start testing examples.

**Comment by armantekinalp** [comment]
Example cases are good and running
