### ISSUE TITLE
Release 0.2.2 Checklist

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/PyElastica#67]
# Release Checklist

- [x] Update RELEASE.md - It should be in based on milestone description.
- [x] Commit the changes: 
```bash
git add RELEASE.md
git commit -m "Changelog for upcoming release <version>"
```
- [x] Final check `README` and `CONTRIBUTING`.
- [x] Bump LICENSE year
- [x] Bump version

### Test
- [x] Run the tests
- [x] Run the formatting
- [x] CI Check
```
python -m pytest
make all
```

### Setup.py
- [x] Update version number in setup.py (or version.py) (can also be minor or major)
- [x] Check if we need to upgrade `REQUIRES_PYTHON` or `REQUIRED` dependencies.
- [x] Check if local installation can be done.
- [x] Update `download_url` in setup
```bash
conda create --name temp
conda activate temp
conda install python==<version>
which pip
pip install .
```

### Documentation and Website
- [x] Check all documentations are updated
- [x] Update version label on documentation
  - [x] docs/conf.py
  - [x] Python version
- [x] Update version label on website
  - [x] Python version

```diff
- BEYOND THIS, EACH STEP SHOULD BE DONE IN SERIAL (STEP_BY_STEPS). -
```

### Last Edit
- [x] Rebase the commit history (should be done by only one person) right before the PR.

### Update
1. [x] Merge the branch to `master`
2. [x] Release on github (v<version>) "include v in front"
3. [x] Release on PyPI by uploading both sdist and wheel:
```
python setup.py sdist
twine upload dist/*
python setup.py bdist_wheel
```

### Final Check
- [x] Test that it pip installs
- [x] Check the PyPI listing page to make sure that the README, release notes, and roadmap display properly.
- [x] Edit the release-page on GitHub. Paste the release notes with a title for the release.
- [x] Check Codcov ID and make sure they are running.
- [x] Make mirror branch in private repo.
